#!/bin/bash
# Copyright (c) 2000-2016 Synology Inc. All rights reserved.

if [ -z "$__INCLUDE_PROJECTS__" ]; then
__INCLUDE_PROJECTS__=defined

PreBuildProjects=""

# Projects that fail to build in parallel
SeqProjs="
	nettle-2.x
	sqlite-3.8.x
	e2fsprogs-1.42
	dbus-1.6.x
	p7zip-4.58
	ncurses-5.5
	libnet-1.x
	busybox-1.16.1
	openssl-1.0.0a
	openssl-1.0.x
	openssl-fips-2.0.x
	libfindhost
	gnu-efi-3.x
	grub-0.97-efi
	e2fsprogs-1.41.10
	e2fsprogs-1.41.12
	krb5-1.12.x
	cyrus-sasl-2.1.22
	net-snmp-5.4.2.1
	net-snmp-5.x
	bind-9.6.1-P1
	parted
	sds_sii
	perl-5.8.6
	synocksum
	memtester
	nss-3.12.4-with-nspr-4.8
	libsynoacl
	libhwcontrol
	openldap-2.3.11
	libgpg-error-1.7
	ipsec-tools-0.7.2
	freeradius-server-2.1.10
	freeradius-server-synovpn
	curlftpfs-0.9.2
	libnl-2.x
	compat-wireless
	ethtool-6
	synosyncfolder
	uClibc-0.9.33
	bash-4.x
	sysstat-10.x
	ctdb-2.5.x
	libplist-1.x
	"
fi
# vim:ft=sh
