#!/bin/bash
# Copyright (c) 2000-2016 Synology Inc. All rights reserved.

if [ -z "$__INCLUDE_VARIABLE__" ]; then
__INCLUDE_VARIABLE__=defined

ConfDir="SynoBuildConf"

# Directory for all compile logs
LogDir="/logs"

# We will install to $TmpInstDir dir and make a tgz file to $TarBallDir
ImageDir="/image"
TarBallDir="${ImageDir}/tarballs"
DebugTarBallDir="${ImageDir}/synodebug"
TmpInstDir="/tmp/_install"

DebDir="/deb"
DebDevBuild="${DebDir}/build"
DebDevDir="${DebDir}/tmpInstallDir"
DebPkgDir="${DebDir}/result"
GlobalDependConf="include/project.depends"

DEFAULT_CCACHE_SIZE="3G"

fi # header guard
# vim:ft=sh
